name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir Ã§alÄ±ÅŸtÄ±r
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: mert-unl
          gif_out_path: dist/snake.gif
          svg_out_path: dist/snake.svg

      - name: Check if files are generated
        run: ls -la dist  # Dosyalar oluÅŸmuÅŸ mu kontrol et

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated Snake Contribution Graph ğŸ"
          branch: output
          file_pattern: dist/snake.*

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

